### ISSUE TITLE
ImportError: cannot import name 'Dialogflow'

### ISSUE THREAD

**Issue by tamilsud** [vkosuri/django-dialogflow#5]
While running your code it shows me a "ImportError: cannot import name 'Dialogflow'" error. but i have installed dialogflow and dialogflow lite...could you please help me on this

**Comment by vkosuri** [comment]
could you post your stack trace of this error?

**Comment by vkosuri** [comment]
Fixed https://github.com/vkosuri/django-dialogflow/commit/4f6537f144fe0da1c95d4d15b98d9fbb68ecba57
